# Generated by Django 3.2.6 on 2022-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default=1, max_length=128, verbose_name='Код подтверждения'),
        ),
    ]
