# Generated by Django 3.2.6 on 2022-06-19 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribing',
            field=models.ManyToManyField(through='users.Subscription', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
