# Generated by Django 3.2.6 on 2022-06-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_subscribing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscribing',
        ),
    ]
